### ISSUE TITLE
fork/exec, exec format error

### ISSUE THREAD

**Issue by Gabology** [hashicorp/vault-auth-plugin-example#1]
Following your tutorial I am getting an error when attempting enable the authentication plugin:

```
Error: Error making API request.

URL: POST http://localhost:8200/v1/sys/auth/example
Code: 400. Errors:

* fork/exec /tmp/vault-plugins/vault-auth-example: exec format error
```

I'm running a vault dev server from the official Vault Docker image version 0.9.0.

**Comment by Gabology** [comment]
Turns out I hadn't set the go compiler to cross compile for Linux :) .

**Comment by seyfbarhoumi** [comment]
I have the same configuration as yours (vault deployed on Docker) and im getting the same error with an auth plugin written with go also, could you please help me with that ? i have no idea about how to set go compiler to cross compile for linux.

**Comment by Gabology** [comment]
@seyfbarhoumi Setting `CGO_ENABLED=0 GOOS=linux` should be enough. There is a good reference [here](https://www.docker.com/blog/containerize-your-go-developer-environment-part-1/).

**Comment by seyfbarhoumi** [comment]
Actually i resolved the problem, i built my own image to compile go code and deliver go binary in a go-alpine environment.

**Comment by DZoubire** [comment]
@seyfbarhoumi could you share the image pls!!
