### ISSUE TITLE
fork/exec, no such file or directory

### ISSUE THREAD

**Issue by sumitb** [hashicorp/vault-auth-plugin-example#10]
Following the tutorial and I am getting an error when attempting enable the authentication plugin:
`/ # vault auth enable -path=foo -plugin-name=foo-auth-plugin plugin`

    Error enabling plugin auth: Error making API request.
    
    URL: POST http://127.0.0.1:8200/v1/sys/auth/iam
    Code: 400. Errors:
    
    * fork/exec /vault/plugins/foo-vault-plugin: no such file or directory

I validated that plugin directory and plugin exists as well
`/ # ls -lh vault/plugins/`

    total 17784
    -rw-rw-r--    1 vault    vault         65 Feb 22 21:19 SHA256
    -rwxr-xr-x    1 vault    vault      17.4M Feb 22 21:19 foo-vault-plugin
Version: Vault v0.10.3

**Comment by sumitb** [comment]
I think I found the issue

`/vault/plugins # ldd foo-vault-plugin`

    	/lib64/ld-linux-x86-64.so.2 (0x7fe85676a000)
    	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe85676a000)
    	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe85676a000)
    Error relocating foo-vault-plugin: __vfprintf_chk: symbol not found
    Error relocating foo-vault-plugin: __fprintf_chk: symbol not found

**Comment by chrishoffman** [comment]
The plugin system has changed quite a bit since the 0.10 and you are likely compiling against the newer APIs that are not available in 0.10.

**Comment by sumitb** [comment]
I thought of that and updated `Gopkg.toml`

    [[constraint]]
      name = "github.com/dgrijalva/jwt-go"
      version = "3.2.0"

    [[constraint]]
      name = "github.com/hashicorp/errwrap"
      version = "1.0.0"

    [[constraint]]
      name = "github.com/hashicorp/vault"
      version = "0.10.3"

    [prune]
      go-tests = true
      unused-packages = true

**Comment by ncabatoff** [comment]
Hi @sumitb,

Do you want to try again with Go 12?  I've converted dependency management from dep to go modules, and provided a `docker-test.sh` script that demonstrates the build/install process using a docker vault.

**Comment by sumitb** [comment]
@ncabatoff Which vault release version is that part of?

**Comment by ncabatoff** [comment]
> @ncabatoff Which vault release version is that part of?

I wasn't talking about a Vault change, but rather about a change to this repo.  (Although Vault is also now using Go modules.)  If you're asking "what Vault version does this repo depend on", it's a little complicated because we don't depend on Vault server versions, which are what's referenced in the [CHANGELOG](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md).  Instead, two modules `api` and `sdk` are now provided by the Vault repo, and they have their own independent versioning.  Those are what this repo depends on.

**Comment by sumitb** [comment]
I need to do the mapping for the vault server version to the corresponding `api` and `sdk` module version then. As eventually, I want the plugin to run properly on the vault server.

Could you point me to where I can find such mapping?

**Comment by kalafut** [comment]
@sumitb Did you get past this issue?

**Comment by sumitb** [comment]
Yes, I did. I'll close this ticket.

**Comment by Falital** [comment]
If someone again faces this issue a quick fix for this is to compile the plugin statically. For example:
``
CGO_ENABLED=0 GOOS=linux go build -o vault-auth-plugin-example cmd/vault-auth-plugin-example/main.go
``
The correct fix would be to compile the library in the same system as vault is running.
