### ISSUE TITLE
Auth plugin under Namespace

### ISSUE THREAD

**Issue by mmzh** [hashicorp/vault-auth-plugin-example#13]
Hi there

how can I catch namespace information in the Plugin code? For example: I’ve enable an Auth Plugin under  “ns1/”, when user authenticates with us through this plugin, they will specify the namespace in the header” X-Vault-Namespace:ns1”,  how Plugin will catch this info, or how Plugin know which Namespace it has been enabled?  I need to catch this info to check policies under the same namespace.

Thank you

Ming

**Comment by kalafut** [comment]
@mmzh Hi. There isn't currently a way to do this, largely by design. The plugin should be designed to operate in a namespace-agnostic manner. Matters of access and polices (and how namespaces might affect them) are left to Vault.
