### ISSUE TITLE
Unable to use plugin with vault_0.9.6

### ISSUE THREAD

**Issue by chegg-scribd-git** [hashicorp/vault-auth-plugin-example#5]
I have tried to 

1.  **deploy** the provided binary with vault0.9.6 version and it failed with following error 

`vault auth enable -path=example -plugin-name=example-auth-plugin plugin` 
`Error enabling plugin auth: Error making API request.`
`URL: POST http://127.0.0.1:8200/v1/sys/auth/example`
` Code: 400. Errors: `
`* Incompatible API version with plugin. Plugin version: 2, Core version: 3`

2. **build** the plugin and got error for SanitizeTTLStr (which was removed recently - https://github.com/hashicorp/vault/pull/4268), not sure whats the alternative to this.

`go build -o /tmp/vault-plugins/vault-auth-example`
  `#### _/tmp/plugin/vault-auth-plugin-example`
`./main.go:78:18: b.SanitizeTTLStr undefined (type *backend has no field or method SanitizeTTLStr)`
`./main.go:111:23: b.SanitizeTTLStr undefined (type *backend has no field or method SanitizeTTLStr)`

_**Can someone help me to deploy it on this version or upgrade the code**_

**Comment by jgiles** [comment]
It looks like the logic in SanitizeTTLStr was phased out in favor of setting `TTL` and `MaxTTL` on `LeaseOptions` and `Secret` structs. Updating this example would help clarify best practice on this.

**Comment by chrishoffman** [comment]
@chegg-scribd-git I just updated the plugin with the latest code, which is 0.10.1.  If you still need to pin to 0.9.6, update the constraint in the Gopkg.toml file to pin to vault 0.9.6.  It appears you are updating to master which changed how TTL handling worked but that didn't land until 0.10.0.
